[package]
name = 'LiquidswapInit'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap = "0xe9d8eecaf7511cbd8c2759ae92504c0207c367be0bd1f9dd13b6a2afd45d0ef0"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
